'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import {
  MENTAL_LOAD_DOMAINS,
  MOODS_DEPRECATED as MOODS,
  LoadIntensityLabel,
  LoadIntensityMap,
  WeeklyCheckinResponse,
} from '@/lib/types';
import { calculateWeeksSinceSemesterStart, type SemesterStartOption } from '@/lib/journey';
import MoodButton from './MoodButton';

interface WeeklyCheckinFlowProps {
  userId: string;
  onComplete?: (response: WeeklyCheckinResponse) => void;
  onSkip?: () => void;
}

/**
 * WeeklyCheckinFlow
 * 
 * Core Anchor interaction: Structured weekly check-in (3-5 minutes)
 * 
 * Flow:
 * 1. Prompt: "What felt heavier than expected this week?"
 * 2. Domain selection: Top 1-2 domains
 * 3. Intensity: Light / Moderate / Heavy
 * 4. Reflection: Guided response
 * 5. Optional: Micro-action suggestion
 * 
 * Non-blocking: Users can skip and access other tools.
 */

export default function WeeklyCheckinFlow({
  userId,
  onComplete,
  onSkip,
}: WeeklyCheckinFlowProps) {
  const router = useRouter();
  const [step, setStep] = useState<
    'intro' | 'domains' | 'intensity' | 'reflection' | 'mood' | 'support-offer' | 'summary'
  >('intro');

  const [selectedDomains, setSelectedDomains] = useState<string[]>([]);
  const [intensity, setIntensity] = useState<LoadIntensityLabel | null>(null);
  const [reflection, setReflection] = useState('');
  const [selectedMood, setSelectedMood] = useState<string | null>(null);
  const [riskTier, setRiskTier] = useState<number>(0);
  const [checkinId, setCheckinId] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const getSemesterWeekContext = async () => {
    try {
      const { data, error: profileError } = await supabase
        .from('users_extended')
        .select('semester_start')
        .eq('user_id', userId)
        .single();

      if (profileError || !data?.semester_start) {
        const fallback = { weekNumber: Math.ceil(new Date().getDate() / 7), semesterYear: new Date().getFullYear() };
        return fallback;
      }

      return calculateWeeksSinceSemesterStart(data.semester_start as SemesterStartOption);
    } catch (err) {
      return { weekNumber: Math.ceil(new Date().getDate() / 7), semesterYear: new Date().getFullYear() };
    }
  };


  const handleDomainToggle = (domainId: string) => {
    setSelectedDomains((prev) => {
      // Limit to 2 domains
      if (prev.includes(domainId)) {
        return prev.filter((d) => d !== domainId);
      }
      if (prev.length >= 2) {
        return prev;
      }
      return [...prev, domainId];
    });
  };

  const handleSubmit = async () => {
    if (!intensity || selectedDomains.length === 0 || !reflection.trim()) {
      setError('Please complete all fields');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const { weekNumber, semesterYear } = await getSemesterWeekContext();

      const { data: { session } } = await supabase.auth.getSession();
      if (!session?.access_token) {
        throw new Error('Not authenticated');
      }

      // Prepare payload
      const payload = {
        week_number: weekNumber,
        semester_year: semesterYear,
        primary_domain_id: selectedDomains[0],
        secondary_domain_id: selectedDomains[1] || null,
        intensity_label: intensity,
        intensity_numeric: LoadIntensityMap[intensity],
        structured_prompt: 'What felt heavier than expected this week?',
        response_text: reflection,
        suggested_action: null, // Can be generated by API later
      };

      const response = await fetch('/api/checkin', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${session.access_token}`,
        },
        body: JSON.stringify(payload),
      });

      if (!response.ok) {
        let errorData: any = {};
        let rawBody = '';
        try {
          rawBody = await response.text();
          errorData = rawBody ? JSON.parse(rawBody) : {};
        } catch (parseErr) {
          errorData = { error: rawBody || response.statusText || `HTTP ${response.status}` };
        }

        console.error('[CHECKIN_CLIENT] Error response:', {
          status: response.status,
          statusText: response.statusText,
          body: rawBody,
          data: errorData,
        });

        throw new Error(errorData?.error || 'Failed to save check-in');
      }

      const responseData = await response.json();
      const risk_tier = responseData.checkin?.risk_tier || 0;
      const checkin_id = responseData.checkin?.id;

      console.log('[CHECKIN_CLIENT] Response received:', {
        risk_tier,
        checkin_id,
        full_response: responseData,
      });

      setRiskTier(risk_tier);
      setCheckinId(checkin_id);

      // Save optional mood snapshot if selected
      if (selectedMood) {
        const { error: moodError } = await supabase.from('mood_entries').insert({
          user_id: userId,
          mood_id: selectedMood,
          text: `Weekly check-in mood - Week ${weekNumber}`,
        });
        if (moodError) {
          console.error('Warning: Failed to save mood snapshot:', {
            message: moodError.message,
            code: moodError.code,
            details: moodError.details,
          });
          // Don't throw - mood is optional, check-in is primary
        }
      }

      // If elevated risk (R2+), offer support contact
      if (risk_tier >= 2) {
        console.log('[CHECKIN_CLIENT] Showing support offer (risk_tier >= 2)');
        setStep('support-offer');
      } else {
        console.log('[CHECKIN_CLIENT] Skipping support offer (risk_tier < 2)');
        setStep('summary');
      }

      // Don't call onComplete here - let user complete the support-offer or summary step
    } catch (err) {
      console.error('Error saving check-in:', err instanceof Error ? err.message : JSON.stringify(err));
      setError(
        err instanceof Error ? err.message : 'Failed to save check-in. Please try again.'
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto p-6 bg-white rounded-lg border border-gray-200">
      {/* Intro Screen */}
      {step === 'intro' && (
        <div className="text-center">
          <h2 className="text-2xl font-bold mb-4 text-gray-900">
            Weekly Check-In
          </h2>
          <p className="text-gray-600 mb-6">
            Take 3–5 minutes to reflect on this week. This helps us understand
            what's putting pressure on you.
          </p>
          <p className="text-sm text-gray-500 mb-8">
            This is for you—not clinical, just honest.
          </p>
          <div className="flex gap-4 justify-center">
            <button
              onClick={() => setStep('domains')}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
            >
              Start Check-In
            </button>
            <button
              onClick={onSkip}
              className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition"
            >
              Skip for Now
            </button>
          </div>
        </div>
      )}

      {/* Domain Selection Screen */}
      {step === 'domains' && (
        <div>
          <h3 className="text-xl font-bold mb-4 text-gray-900">
            What felt heavier than expected this week?
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            Select your top 1–2 areas (choose the most relevant):
          </p>
          <div className="grid grid-cols-2 gap-3 mb-8">
            {MENTAL_LOAD_DOMAINS.map((domain) => (
              <button
                key={domain.id}
                onClick={() => handleDomainToggle(domain.id)}
                className={`p-4 rounded-lg border-2 transition font-semibold ${
                  selectedDomains.includes(domain.id)
                    ? 'border-blue-600 bg-blue-50 text-blue-900'
                    : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300'
                }`}
              >
                <div className="text-2xl mb-2">{domain.emoji}</div>
                <div className="text-sm">{domain.label}</div>
              </button>
            ))}
          </div>
          <button
            onClick={() => setStep('intensity')}
            disabled={selectedDomains.length === 0}
            className="w-full px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
          >
            Next: Intensity
          </button>
        </div>
      )}

      {/* Intensity Selection Screen */}
      {step === 'intensity' && (
        <div>
          <h3 className="text-xl font-bold mb-4 text-gray-900">
            How heavy did that feel?
          </h3>
          <p className="text-sm text-gray-600 mb-8">
            Choose one (Light, Moderate, or Heavy):
          </p>
          <div className="grid grid-cols-3 gap-4 mb-8">
            {(['Light', 'Moderate', 'Heavy'] as LoadIntensityLabel[]).map(
              (label) => (
                <button
                  key={label}
                  onClick={() => setIntensity(label)}
                  className={`p-6 rounded-lg border-2 transition font-semibold text-center ${
                    intensity === label
                      ? 'border-blue-600 bg-blue-50 text-blue-900'
                      : 'border-gray-200 bg-white text-gray-700 hover:border-gray-300'
                  }`}
                >
                  <div className="text-2xl mb-2">
                    {label === 'Light' && '🌤️'}
                    {label === 'Moderate' && '⛅'}
                    {label === 'Heavy' && '⛈️'}
                  </div>
                  <div>{label}</div>
                </button>
              )
            )}
          </div>
          <button
            onClick={() => setStep('reflection')}
            disabled={!intensity}
            className="w-full px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
          >
            Next: Reflection
          </button>
        </div>
      )}

      {/* Reflection Screen */}
      {step === 'reflection' && (
        <div>
          <h3 className="text-xl font-bold mb-4 text-gray-900">
            Tell us a bit more
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            What's one thing that made this week harder than you expected?
          </p>
          <textarea
            value={reflection}
            onChange={(e) => setReflection(e.target.value)}
            placeholder="Be specific—the more detail, the better we can help..."
            className="w-full p-4 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-600 mb-6"
            rows={6}
          />
          {error && <p className="text-red-600 text-sm mb-4">{error}</p>}
          <div className="flex gap-4">
            <button
              onClick={() => setStep('intensity')}
              className="flex-1 px-4 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition"
            >
              Back
            </button>
            <button
              onClick={() => setStep('mood')}
              disabled={!reflection.trim()}
              className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
            >
              Next: Mood Snapshot
            </button>
          </div>
        </div>
      )}

      {/* Optional Mood Snapshot Screen */}
      {step === 'mood' && (
        <div>
          <h3 className="text-xl font-bold mb-4 text-gray-900">
            How are you feeling right now?
          </h3>
          <p className="text-sm text-gray-600 mb-6">
            Optional: Capture your mood to pair with this check-in. This helps track patterns over time.
          </p>
          <div className="grid grid-cols-3 gap-4 mb-8">
            {MOODS.map((mood) => (
              <MoodButton
                key={mood.id}
                mood={mood}
                isSelected={selectedMood === mood.id}
                onClick={() => setSelectedMood(mood.id)}
              />
            ))}
          </div>
          {error && <p className="text-red-600 text-sm mb-4">{error}</p>}
          <div className="flex gap-4">
            <button
              onClick={() => setStep('reflection')}
              className="flex-1 px-4 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition"
            >
              Back
            </button>
            <button
              onClick={handleSubmit}
              disabled={loading}
              className="flex-1 px-4 py-3 bg-gray-600 text-white rounded-lg font-semibold hover:bg-gray-700 transition disabled:opacity-50"
            >
              {loading ? 'Saving...' : 'Skip Mood'}
            </button>
            <button
              onClick={handleSubmit}
              disabled={loading || !selectedMood}
              className="flex-1 px-4 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
            >
              {loading ? 'Saving...' : 'Save Check-In'}
            </button>
          </div>
        </div>
      )}

      {/* Support Offer Screen (shown for R2+ risk tiers) */}
      {step === 'support-offer' && (
        <div>
          <div className="text-center mb-6">
            <div className="text-4xl mb-4">💙</div>
            <h3 className="text-xl font-bold text-gray-900 mb-4">
              We're here if you need support
            </h3>
            <p className="text-gray-700 mb-4">
              It sounds like things have been particularly challenging. 
              You don't have to go through this alone.
            </p>
          </div>

          {/* In-app crisis resources */}
          <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg mb-6">
            <p className="text-sm font-semibold text-blue-900 mb-2">
              Immediate Support Resources
            </p>
            <ul className="text-sm text-blue-800 space-y-2">
              <li>🇮🇪 <strong>Samaritans Ireland:</strong> 116 123 (24/7, free)</li>
              <li>🇮🇪 <strong>Pieta House:</strong> 1800 247 247 (crisis support)</li>
              <li>🌍 <strong>Crisis Text Line:</strong> Text "HELLO" to 50808</li>
            </ul>
          </div>

          {/* Opt-in for support contact */}
          <div className="p-4 bg-gray-50 border border-gray-200 rounded-lg mb-6">
            <p className="text-sm font-semibold text-gray-900 mb-2">
              Would you like someone from your institution's wellbeing team to reach out?
            </p>
            <p className="text-xs text-gray-600 mb-4">
              If you opt in, a trained support staff member will be notified and may 
              contact you to offer resources or schedule a confidential conversation. 
              This is completely voluntary.
            </p>
          </div>

          {error && <p className="text-red-600 text-sm mb-4">{error}</p>}

          <div className="flex flex-col gap-3">
            <button
              onClick={async () => {
                setLoading(true);
                try {
                  // Create consent + support request
                  const { data: { session } } = await supabase.auth.getSession();
                  if (!session?.access_token) {
                    throw new Error('Not authenticated');
                  }

                  const response = await fetch('/api/consent/create-support-request', {
                    method: 'POST',
                    headers: {
                      'Content-Type': 'application/json',
                      Authorization: `Bearer ${session.access_token}`,
                    },
                    body: JSON.stringify({
                      checkin_id: checkinId,
                      request_type: 'contact_me',
                      risk_tier: riskTier,
                    }),
                  });

                  if (!response.ok) {
                    throw new Error('Failed to create support request');
                  }

                  setStep('summary');
                } catch (err) {
                  console.error('Error creating support request:', err);
                  setError(err instanceof Error ? err.message : 'Failed to request support');
                } finally {
                  setLoading(false);
                }
              }}
              disabled={loading}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition disabled:opacity-50"
            >
              {loading ? 'Processing...' : 'Yes, please have someone reach out'}
            </button>
            <button
              onClick={() => setStep('summary')}
              disabled={loading}
              className="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg font-semibold hover:bg-gray-300 transition disabled:opacity-50"
            >
              No thanks, I'm okay for now
            </button>
          </div>

          <p className="text-xs text-gray-500 mt-4 text-center">
            Your privacy matters. Opting in creates a consent record that you can 
            withdraw at any time from your settings.
          </p>
        </div>
      )}

      {/* Summary/Confirmation Screen */}
      {step === 'summary' && (
        <div className="text-center">
          <div className="text-5xl mb-4">✓</div>
          <h2 className="text-2xl font-bold mb-4 text-gray-900">
            Check-in saved
          </h2>
          <p className="text-gray-600 mb-8">
            Thanks for checking in. We're tracking these patterns to help you
            stay steady.
          </p>
          <div className="flex gap-4 justify-center">
            <button
              onClick={() => {
                const domain = selectedDomains[0] || 'general';
                router.push(`/chat?source=checkin&domain=${domain}`);
              }}
              className="px-6 py-3 bg-gray-600 text-white rounded-lg font-semibold hover:bg-gray-700 transition"
            >
              Talk it through
            </button>
            <button
              onClick={() => {
                if (onComplete) {
                  onComplete({} as WeeklyCheckinResponse);
                }
              }}
              className="px-6 py-3 bg-blue-600 text-white rounded-lg font-semibold hover:bg-blue-700 transition"
            >
              Done
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
